'''
DEVELOPED BY: TAANISHQ SETHI
'''



import pymysql
db=pymysql.connect(host="localhost", \
    user="root",password = "mysql")
MyCur= db.cursor()
try:
    MyCur.execute("CREATE DATABASE PY_PROJECT")
    print("THE DATABASE CREATED......")
    print()
except:
    print("THE DATABSE EXISTS.....")
    print()

MyCur.execute('USE PY_PROJECT')

try:
    MyCur.execute("CREATE TABLE FOODITEMS (SNO INT PRIMARY KEY,\
      FOODNAME CHAR(25),PRICE DECIMAL(3,2),CUISINE CHAR(15))")
    print("FOODITEMS Created")
    print()
except:
    print("TABLE FOODITEMS ALREADY EXISTS.....")
    print()



try:
    MyCur.execute("CREATE TABLE CUSTOMERS (CNAME CHAR(25) NOT NULL,\
        ADDRESS CHAR(100)UNIQUE KEY , Mbno DECIMAL(10) PRIMARY KEY,DISTRICT CHAR(20))")
    print("CUSTOMERS CREATED....")
    print()
except:
    print("TABLE CUSTOMERS ALREADY EXISTS.....")


N=MyCur.execute('SELECT * FROM FOODITEMS')
if N==0:
    MyCur.execute("INSERT INTO FOODITEMS VALUES(1,'DAAL MAKHNI',200,'INDIAN')")
    MyCur.execute("INSERT INTO FOODITEMS VALUES(2,'CHICKEN TIKKA',120,'INDIAN')")
    MyCur.execute("INSERT INTO FOODITEMS VALUES(3,'BUTTER NAAN',75,'INDIAN')")
    MyCur.execute("INSERT INTO FOODITEMS VALUES(4,'PANEER TIKKA',100,'INDIAN')")
    MyCur.execute("INSERT INTO FOODITEMS VALUES(5,'HAKKAH NOODLES',150,'CHINESE')")
    MyCur.execute("INSERT INTO FOODITEMS VALUES(6,'VEG MANCHURIAN',175,'CHINESE')")
    MyCur.execute("INSERT INTO FOODITEMS VALUES(7,'CHILLY CHICKEN',170,'CHINESE')")
    MyCur.execute("INSERT INTO FOODITEMS VALUES(8,'CHICKEN BIRYANI',220,'MUGHLAI')")
    MyCur.execute("INSERT INTO FOODITEMS VALUES(9,'MUTTON GULLOTI',180,'MUGHLAI')")
    MyCur.execute("INSERT INTO FOODITEMS VALUES(10,'KHAMEERI ROTI',100,'MUGHLAI')")
    db.commit()
    print('Values inserted!!')

X=MyCur.execute('SELECT * FROM CUSTOMERS')
if X==0:
    MyCur.execute("INSERT INTO CUSTOMERS VALUES('TAANISHQ SETHI','MALVIYA NAGAR',9810273638,'SOUTH DELHI')")
    MyCur.execute("INSERT INTO CUSTOMERS VALUES('ARNAV SRIVASTAV','DILSHAD GARDERN',8810293456,'EAST DELHI')")
    MyCur.execute("INSERT INTO CUSTOMERS VALUES('KUSHAGRA MIGLANI','EAST OF KAILASH',9563210478,'SOUTH DELHI')")
    MyCur.execute("INSERT INTO CUSTOMERS VALUES('RAJDEEP TIWARI','GREATER KAILASH 2',7894561230,'SOUTH DELHI')")
    MyCur.execute("INSERT INTO CUSTOMERS VALUES('ABHI KANSAL','MODEL TOWN',8527419631,'NORTH DELHI')")
    db.commit()
    print('Values inserted!!')
